apiVersion: v1
kind: Service
metadata:
  name: {{ include "manifests.fullname" . }}
  labels:
    {{- include "manifests.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "manifests.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.containerPort }}
