# Default values for manifests.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: IfNotPresent

containerPort: 80

tlsIssuer: letsencrypt
